### ISSUE TITLE
Getting Started problem?

### ISSUE THREAD

**Issue by ajs6f** [cumulusrdf/cumulusrdf#89]
Having cloned the source and successfully run 'mvn install', I `cd` into `cumulusrdf-web-module` and try `mvn clean cassandra:stop cassandra:start tomcat7:run` as advised on the Getting Started wiki page, but the run errors out with:
```
[ERROR] Failed to execute goal org.codehaus.mojo:cassandra-maven-plugin:2.1.7-1:start (default-cli) on project cumulusrdf-web-module: script /private/tmp/cumulusrdf/cumulusrdf-web-module/src/cassandra/cql/load.cql does not exist. -> [Help 1]
```
and indeed, that file does not exist. A fuller log is available [here](https://gist.github.com/ajs6f/2f65f16bb9a4e860f48e). Am I looking in the wrong place for getting started instructions? Thanks!

**Comment by agazzarini** [comment]
Hi @ajs6f,* <https://github.com/ajs6f> *
I just tried to start CumulusRDF and I get the same problem. Unfortunately
it's not just a matter of Wiki instructions. With the latest commits I
integrated the Farsandra plugin for doing integration tests and as
consequence of that, the Cassandra Maven needs to be removed from our maven
configuration. There's also a problem with the Wiki, but that is because it
has been imported roughly from Google Project, so it contains instructions
that were valid at that time (as you can see we were using SVN).

So, I need to have a deeper look at the build cycle in order to fix those
dependencies. Then I will correct the WIki.
I will keep you informed about this task.

Many thanks for entering this.

Andrea


2015-12-18 20:23 GMT+01:00 A. Soroka <notifications@github.com>:

**Comment by ajs6f** [comment]
Okay, that makes sense. Thanks for being so responsive about this. I'll take the opportunity to survey the code itself!

**Comment by agazzarini** [comment]
Hi @ajs6f I just commited a couple of fixes that shoul solve the problem. I also updated the Getting Started [1] page. 

Let me know if we can close this issue or improve something else.

--------------------------
[1] https://github.com/cumulusrdf/cumulusrdf/wiki/GettingStarted

**Comment by ajs6f** [comment]
Looks great! We can close this issue. It would be nice to use something like Codehaus Cargo instead of the Tomcat plugin so that different containers could be used. I'll try and make a PR for that, and I'll open a ticket for that when I have something to send with it.

**Comment by agazzarini** [comment]
+1 for Cargo. I'm closing this issue.
